apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: example-es-cluster
spec:
  kibana:
    image: upmcenterprises/kibana:5.3.1
  elastic-search-image: upmcenterprises/docker-elasticsearch-kubernetes:5.3.1
  client-node-replicas: 1
  master-node-replicas: 1
  data-node-replicas: 3
  network-host: 0.0.0.0
  zones: []
  data-volume-size: 10Gi
  java-options: "-Xms256m -Xmx256m"
  snapshot:
    scheduler-enabled: false
    bucket-name: elasticsnapshots99
    cron-schedule: "@every 2m"
  storage:
    type: standard
    storage-class-version: volume.alpha.kubernetes.io/storage-class
