apiVersion: v1
entries:
  elasticsearch:
  - apiVersion: v1
    created: "2019-08-09T11:48:21.462343+01:00"
    description: A Helm chart for Elasticsearch cluster
    digest: 643d5c803963b18edfe18b15d557cc71d4e3e0e9cf988c6426d7972714638c5b
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v1
    created: "2019-08-09T11:48:21.46212+01:00"
    description: A Helm chart for Elasticsearch cluster
    digest: caebb410909e560ec9664d1d7f2af6be57532b4c3eebbaad6c5a837f8344985d
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v1
    created: "2019-08-09T11:48:21.461535+01:00"
    description: A Helm chart for Elasticsearch cluster
    digest: 9920b21e981186f20195c4c8871da7d3872527df269d990ab57fffcec3014cf1
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v1
    created: "2019-08-09T11:48:21.461231+01:00"
    description: A Helm chart for Elasticsearch cluster
    digest: 3437e67980b4369ae18d10bbb64ad62b9e6af6da0d11dc79628d39ce00ba06fa
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    created: "2019-08-09T11:48:21.460186+01:00"
    description: A Helm chart for Elasticsearch cluster
    digest: 2dee389105b87cfaf0150f4215f927bcb79c22f877e801850419a17284191343
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v1
    created: "2019-08-09T11:48:21.459669+01:00"
    description: A Helm chart for Elasticsearch cluster
    digest: 398bcb148fe08fe7ae0d5918af25efd28fe60fd77f47ae2760f1347643d76aab
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    created: "2019-08-09T11:48:21.459067+01:00"
    description: A Helm chart for Elasticsearch cluster
    digest: de2209bffb7a05c436354b2514abadacb83007dd0d59941cb78b340c6db9cc52
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: "2019-08-09T11:48:21.458516+01:00"
    description: A Helm chart for Elasticsearch cluster
    digest: 37bc0b51a58e73e29221062df665ce7234f36689dc7051164141680b6c0096bd
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.0.tgz
    version: 0.1.0
  elasticsearch-operator:
  - apiVersion: v1
    created: "2019-08-09T11:48:21.464539+01:00"
    description: A Helm chart for Elasticsearch operator
    digest: b0097f1f8f70d7dc5230ab9f75569eb6894198ac0b9dd6ef3fc668cec9b1cb7e
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    created: "2019-08-09T11:48:21.464283+01:00"
    description: A Helm chart for Elasticsearch operator
    digest: 07a48f24d2a1e86e41acfb427a4e479b35067042a48385bd4df2caa7b38d9787
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v1
    created: "2019-08-09T11:48:21.463831+01:00"
    description: A Helm chart for Elasticsearch operator
    digest: bf9e1bf0f857acdbb281ac2480add1f5a9d33b303e3cba4fffdc6921cbf27f5f
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    created: "2019-08-09T11:48:21.463377+01:00"
    description: A Helm chart for Elasticsearch operator
    digest: 65b48cf707f5bd8170a22f4827236c36591dde215712b29a8df0136e64d57a49
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: "2019-08-09T11:48:21.462871+01:00"
    description: A Helm chart for Elasticsearch operator
    digest: 1c21e32521c3843f04e38892ea432a2529d819019f7bb919cc48bedf9a629400
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.0.tgz
    version: 0.1.0
generated: "2019-08-09T11:48:21.457456+01:00"
